"""empty message

Revision ID: 6c684c7e4df2
Revises: d660466dbefd
Create Date: 2024-10-10 16:04:49.893535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c684c7e4df2'
down_revision = 'd660466dbefd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('isActive', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['isActive'])
        batch_op.create_unique_constraint(None, ['password'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('isActive')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
